--  Table for user
CREATE TABLE IF NOT EXISTS user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  user_name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email varchar(255) NOT NULL
);

-- Table for role
CREATE TABLE IF NOT EXISTS role (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  role_name VARCHAR(255) NOT NULL
);

-- Table for relation user and role
CREATE TABLE IF NOT EXISTS user_role (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id),
  FOREIGN KEY (role_id) REFERENCES role (id)
);

-- TODO create table label for icon item_category and item

-- Table for items category
CREATE TABLE IF NOT EXISTS item_category (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  category_name VARCHAR(255) NOT NULL
);

-- Table for item
CREATE TABLE IF NOT EXISTS item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  item_title VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  item_category_id BIGINT NOT NULL,
  FOREIGN KEY (item_category_id) REFERENCES item_category (id)
);

-- Table for picnic
CREATE TABLE IF NOT EXISTS picnic (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  picnic_title VARCHAR(255) NOT NULL
);

-- Table for picnic's item

CREATE TABLE IF NOT EXISTS picnic_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  picnic_id BIGINT NOT NULL,
  item_id BIGINT NOT NULL,
  FOREIGN KEY (picnic_id) REFERENCES picnic (id),
  FOREIGN KEY (item_id) REFERENCES item (id)
);
